// Generated by atcc.
#include <stdint.h>
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef float f32;
typedef double f64;


typedef struct string string;


typedef struct Array_0 {
    u32 length;
    string *data;
} Array_0;

struct string {
    /* 0x0000 */u32 length;
    /* 0x0004 */u8* data;
};



void __atcc_init_globals(void);
i32 Main(Array_0 param0);

static char GLOBAL_VARIABLES[0];

void __atcc_init_globals(void) {
__block0: ;
}

i32 Main(Array_0 param0) {
    char STACK[4];
__block0: ;
    *((i32*)(&STACK[0])) = ((i32)(1));
    i32 V0 = *((i32*)(&STACK[0]));
    i32 V1 =  - V0;
    *((i32*)(&STACK[0])) = V1;
    i32 V2 = *((i32*)(&STACK[0]));
    *((i32*)(&STACK[0])) = V2;
    i32 V3 = *((i32*)(&STACK[0]));
    i32 V4 = -V3;
    *((i32*)(&STACK[0])) = V4;
    i32 V5 = *((i32*)(&STACK[0]));
    i32 V6 = !V5;
    *((i32*)(&STACK[0])) = V6;
    *((i32*)(&STACK[0])) = ((i32)(0));
    i32 V7 = *((i32*)(&STACK[0]));
    return V7;
}


int main(int argc, char **argv) {
    __atcc_init_globals();
    return Main();
}
