// Generated by atcc.
#include <stdint.h>
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef float f32;
typedef double f64;


void __atcc_init_globals(void) {
__block0: ;
}

void Test0(void) {
__block0: ;
}

void Test1(i32 param0) {
__block0: ;
}

i32 Test2(i32 param0) {
__block0: ;
    return ((i32)(0));
}

i32 Test3(i32 param0) {
__block0: ;
    i32 V1 = ((i32)(5)) + param0;
    return V1;
}

i32 Test4(i32 param0) {
    char STACK[4];
__block0: ;
    *((i32*)(&STACK[0])) = param0;
    i32 V0 = *((i32*)(&STACK[0]));
    return V0;
}

i32 Test051(void) {
u32 V6;
__block0: ;
    i32 V3 = ((i32)(1)) != ((u32)(0));
    if (V3) goto __block3; else goto __block1;
__block1: ;
    i32 V5 = ((i32)(2)) != ((u32)(0));
    if (V5) goto __block3; else goto __block2;
__block2: ;
    V6 = ((u32)(0)); goto __block4;
__block3: ;
    V6 = ((u32)(1)); goto __block4;
__block4: ;
    return V6;
}

i32 Test052(void) {
u32 V6;
__block0: ;
    i32 V3 = ((i32)(1)) != ((u32)(0));
    if (V3) goto __block1; else goto __block2;
__block1: ;
    i32 V5 = ((i32)(2)) != ((u32)(0));
    if (V5) goto __block3; else goto __block2;
__block2: ;
    V6 = ((u32)(0)); goto __block4;
__block3: ;
    V6 = ((u32)(1)); goto __block4;
__block4: ;
    return V6;
}

i32 Test053(void) {
i32 V4;
__block0: ;
    i32 V1 = ((i32)(1)) != ((u32)(0));
    if (V1) goto __block1; else goto __block2;
__block1: ;
    V4 = ((i32)(1)); goto __block3;
__block2: ;
    V4 = ((i32)(1)); goto __block3;
__block3: ;
    return V4;
}

i32 Test054(void) {
u32 V10;
i32 V6;
__block0: ;
    i32 V3 = ((i32)(1)) != ((u32)(0));
    if (V3) goto __block5; else goto __block6;
__block1: ;
    i32 V9 = ((i32)(2)) != ((u32)(0));
    if (V9) goto __block3; else goto __block2;
__block2: ;
    V10 = ((u32)(0)); goto __block4;
__block3: ;
    V10 = ((u32)(1)); goto __block4;
__block4: ;
    return V10;
__block5: ;
    V6 = ((i32)(1)); goto __block7;
__block6: ;
    V6 = ((i32)(1)); goto __block7;
__block7: ;
    i32 V7 = V6 != ((u32)(0));
    if (V7) goto __block3; else goto __block1;
}

i32 Test055(void) {
u32 V10;
i32 V6;
__block0: ;
    i32 V3 = ((i32)(1)) != ((u32)(0));
    if (V3) goto __block5; else goto __block6;
__block1: ;
    i32 V9 = ((i32)(2)) != ((u32)(0));
    if (V9) goto __block3; else goto __block2;
__block2: ;
    V10 = ((u32)(0)); goto __block4;
__block3: ;
    V10 = ((u32)(1)); goto __block4;
__block4: ;
    return V10;
__block5: ;
    V6 = ((i32)(1)); goto __block7;
__block6: ;
    V6 = ((i32)(1)); goto __block7;
__block7: ;
    i32 V7 = V6 != ((u32)(0));
    if (V7) goto __block1; else goto __block2;
}

i32 Test056(void) {
u32 V14;
i32 V6;
i32 V12;
__block0: ;
    i32 V3 = ((i32)(1)) != ((u32)(0));
    if (V3) goto __block5; else goto __block6;
__block1: ;
    i32 V9 = ((i32)(1)) != ((u32)(0));
    if (V9) goto __block8; else goto __block9;
__block2: ;
    V14 = ((u32)(0)); goto __block4;
__block3: ;
    V14 = ((u32)(1)); goto __block4;
__block4: ;
    return V14;
__block5: ;
    V6 = ((i32)(1)); goto __block7;
__block6: ;
    V6 = ((i32)(1)); goto __block7;
__block7: ;
    i32 V7 = V6 != ((u32)(0));
    if (V7) goto __block3; else goto __block1;
__block8: ;
    V12 = ((i32)(1)); goto __block10;
__block9: ;
    V12 = ((i32)(1)); goto __block10;
__block10: ;
    i32 V13 = V12 != ((u32)(0));
    if (V13) goto __block3; else goto __block2;
}

i32 Test057(void) {
u32 V14;
i32 V6;
i32 V12;
__block0: ;
    i32 V3 = ((i32)(1)) != ((u32)(0));
    if (V3) goto __block5; else goto __block6;
__block1: ;
    i32 V9 = ((i32)(1)) != ((u32)(0));
    if (V9) goto __block8; else goto __block9;
__block2: ;
    V14 = ((u32)(0)); goto __block4;
__block3: ;
    V14 = ((u32)(1)); goto __block4;
__block4: ;
    return V14;
__block5: ;
    V6 = ((i32)(1)); goto __block7;
__block6: ;
    V6 = ((i32)(1)); goto __block7;
__block7: ;
    i32 V7 = V6 != ((u32)(0));
    if (V7) goto __block1; else goto __block2;
__block8: ;
    V12 = ((i32)(1)); goto __block10;
__block9: ;
    V12 = ((i32)(1)); goto __block10;
__block10: ;
    i32 V13 = V12 != ((u32)(0));
    if (V13) goto __block3; else goto __block2;
}

i32 Test5(i32 param0) {
    char STACK[4];
__block0: ;
    i32 V1 = param0 - ((i32)(1));
    *((i32*)(&STACK[0])) = V1;
    i32 V3 = *((i32*)(&STACK[0]));
    i32 V5 = -((i32)(1));
    i32 V6 = V3 == V5;
    i32 V7 = V6 != ((u32)(0));
    if (V7) goto __block1; else goto __block2;
__block1: ;
    return ((i32)(3));
__block2: ;
    i32 V10 = *((i32*)(&STACK[0]));
    i32 V12 = V10 == ((i32)(0));
    i32 V13 = V12 != ((u32)(0));
    if (V13) goto __block4; else goto __block5;
__block3: ;
    return ((i32)(8));
__block4: ;
    return ((i32)(4));
__block5: ;
    goto __block6;
__block6: ;
    goto __block3;
}

i32 Test51(i32 param0) {
u32 V7;
__block0: ;
    i32 V4 = param0 >= ((i32)(20));
    i32 V5 = V4 != ((u32)(0));
    if (V5) goto __block4; else goto __block5;
__block1: ;
    i32 V12 = param0 - ((i32)(1));
    return V12;
__block2: ;
    i32 V14 = param0 + ((i32)(1));
    return V14;
__block3: ;
__block4: ;
    i32 V6 = param0 != ((u32)(0));
    if (V6) goto __block6; else goto __block5;
__block5: ;
    V7 = ((u32)(0)); goto __block7;
__block6: ;
    V7 = ((u32)(1)); goto __block7;
__block7: ;
    u32 V9 = V7 <= ((i32)(30));
    u32 V10 = V9 != ((u32)(0));
    if (V10) goto __block1; else goto __block2;
}

i32 Test52(i32 param0) {
    char STACK[4];
__block0: ;
    *((i32*)(&STACK[0])) = param0;
    *((i32*)(&STACK[0])) = ((i32)(10));
    i32 V1 = *((i32*)(&STACK[0]));
    return V1;
}

i32 Test53(i32 param0) {
    char STACK[4];
__block0: ;
    *((i32*)(&STACK[0])) = param0;
    i32 V0 = *((i32*)(&STACK[0]));
    u64 V1 = (u64) V0;
    *((u64*)(&GLOBAL_VARIABLES[0])) = V1;
    u64 V2 = *((u64*)(&GLOBAL_VARIABLES[0]));
    return V2;
}

