name: test

# Needs: cmake, make, gcc, g++ and python3

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y cmake
        - name: Build and test
          run: |
            python3 tests/runner.py ci